import type { Metadata } from "next";
import "@/styles/global.scss";
import ReactQueryProvider from "./providers";
export const metadata: Metadata = {
  title: "indition customer",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryProvider>{children}</ReactQueryProvider>
      </body>
    </html>
  );
}
